Feature/tags
redeye-framework/Redeye pull request #21
Opened 2023-06-26 12:51 UTC by sisitrs2

Added tags for server. 
This could be used for any purpose, signaling the OS or AV were in mind during the development.

2023-06-28 22:34 UTC, Sh3lldor commented on static/css/servers.css
> +#tag-box {
Maybe we should make the box bigger

2023-06-28 22:35 UTC, Sh3lldor requested changes

2023-06-28 22:35 UTC, Sh3lldor commented on static/css/servers.css
> +.checkbox-container .checkbox-indicator {
border-radius maybe?

2023-06-30 11:49 UTC, sisitrs2 commented on static/css/servers.css
> +#tag-box {
Done

2023-06-30 11:49 UTC, sisitrs2 commented on static/css/servers.css
> +.checkbox-container .checkbox-indicator {
Done

2023-06-30 12:17 UTC, Sh3lldor approved these changes
LGTM!

2023-06-30 12:19 UTC, merged